channels:
  - conda-forge
dependencies:
  - catch2
  - cmake
  - doxygen
  - h5py
  - highfive
  - mathjax
  - ninja
  - numpy
  - prrng
  - pybind11
  - python
  - python-prrng
  - setuptools_scm
  - xsimd
  - xtensor
  - xtensor-python
