channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor

  # optional dependencies
  - xsimd

  # build tools
  - cmake
  - setuptools_scm

  # Python API
  - python
  - pyxtensor

  # run tests
  - catch2
  - highfive
  - numpy
  - h5py

  # build docs
  - doxygen
  - mathjax
